import { existsSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  lintShotsFile,
  lintStillsFile,
  loadShotsFile,
  loadStillsFile,
} from "./shots.js";

const repoRoot = join(import.meta.dirname, "..");

// One example film, two cuts: lighthouse on 2.0 (the complete pipeline) and
// the same story restructured as 30s acts on 2.5. Both are the first thing a
// new user or agent copies, so both meet the bar the CLI enforces.
const SHOTS_FILES = [
  "examples/shots-2-5.json",
  "films/lighthouse/shots.json",
] as const;

/**
 * Examples that must parse but legitimately trip a best-practice warning.
 *
 * `shots-h3.json` is text-to-video, which is H3's headline mode (native audio,
 * no keyframe needed) and exactly what the linter's "anchor every shot to a
 * literal keyframe" advice argues against. The advice is right for Seedance
 * and the example is right for H3, so it validates here and is deliberately
 * kept out of the zero-warning list rather than papered over with a fake
 * reference URL.
 */
const SCHEMA_ONLY_SHOTS_FILES = ["examples/shots-h3.json"] as const;

const STILLS_FILES = ["films/lighthouse/stills.json"] as const;

// The shipped example and demo film are the first thing a new user copies, so
// they have to satisfy the same schema and best-practice bar the CLI enforces.
describe("shipped examples", () => {
  it.each(SHOTS_FILES)("%s validates against the shots schema", async (rel) => {
    const file = await loadShotsFile(join(repoRoot, rel));
    expect(file.shots.length).toBeGreaterThan(0);
  });

  it.each(SCHEMA_ONLY_SHOTS_FILES)(
    "%s validates against the shots schema",
    async (rel) => {
      const file = await loadShotsFile(join(repoRoot, rel));
      expect(file.shots.length).toBeGreaterThan(0);
    }
  );

  it.each(SHOTS_FILES)("%s lints without warnings", async (rel) => {
    const warnings = lintShotsFile(await loadShotsFile(join(repoRoot, rel)));
    expect(warnings).toEqual([]);
  });

  it.each(STILLS_FILES)(
    "%s validates against the stills schema",
    async (rel) => {
      const file = await loadStillsFile(join(repoRoot, rel));
      expect(file.stills.length).toBeGreaterThan(0);
    }
  );

  it.each(STILLS_FILES)("%s lints without warnings", async (rel) => {
    const warnings = lintStillsFile(await loadStillsFile(join(repoRoot, rel)));
    expect(warnings).toEqual([]);
  });

  // Every keyframe a shot points at must be something `vs stills` actually
  // produces, otherwise the walkthrough breaks on a missing file.
  it("lighthouse shot keyframes are all generated by its stills file", async () => {
    const shots = await loadShotsFile(
      join(repoRoot, "films/lighthouse/shots.json")
    );
    const stills = await loadStillsFile(
      join(repoRoot, "films/lighthouse/stills.json")
    );
    const outputDir = (stills.outputDir ?? "./stills").replace(/\/$/u, "");
    const produced = new Set(
      stills.stills.map((still) => `${outputDir}/${still.id}.png`)
    );
    expect(shots.shots).toHaveLength(12);
    expect(stills.stills).toHaveLength(12);
    for (const shot of shots.shots) {
      for (const ref of shot.references ?? []) {
        expect(produced).toContain(ref.url);
      }
    }
  });

  it("lighthouse ships the complete planning ladder", () => {
    for (const file of [
      "treatment.md",
      "style-bible.md",
      "beat-sheet.md",
      "screenplay.md",
      "shot-list.md",
    ]) {
      expect(existsSync(join(repoRoot, "films/lighthouse", file))).toBe(true);
    }
  });
});
