import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { lintShotsFile, loadShotsFile, loadStillsFile } from "./shots.js";

const repoRoot = join(import.meta.dirname, "..");

const SHOTS_FILES = [
  "examples/shots.json",
  "films/lighthouse/shots.json",
] as const;

const STILLS_FILES = ["films/lighthouse/stills.json"] as const;

// The shipped example and demo film are the first thing a new user copies, so
// they have to satisfy the same schema and best-practice bar the CLI enforces.
describe("shipped examples", () => {
  it.each(SHOTS_FILES)("%s validates against the shots schema", async (rel) => {
    const file = await loadShotsFile(join(repoRoot, rel));
    expect(file.shots.length).toBeGreaterThan(0);
  });

  it.each(SHOTS_FILES)("%s lints without warnings", async (rel) => {
    const warnings = lintShotsFile(await loadShotsFile(join(repoRoot, rel)));
    expect(warnings).toEqual([]);
  });

  it.each(STILLS_FILES)(
    "%s validates against the stills schema",
    async (rel) => {
      const file = await loadStillsFile(join(repoRoot, rel));
      expect(file.stills.length).toBeGreaterThan(0);
    }
  );

  // Every keyframe a shot points at must be something `vs stills` actually
  // produces, otherwise the walkthrough breaks on a missing file.
  it("lighthouse shot keyframes are all generated by its stills file", async () => {
    const shots = await loadShotsFile(
      join(repoRoot, "films/lighthouse/shots.json")
    );
    const stills = await loadStillsFile(
      join(repoRoot, "films/lighthouse/stills.json")
    );
    const produced = new Set(
      stills.stills.map((still) => `./stills/${still.id}.png`)
    );
    for (const shot of shots.shots) {
      for (const ref of shot.references ?? []) {
        expect(produced).toContain(ref.url);
      }
    }
  });
});
